////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#include <ZionBase.h>
#include <AsyncRPCImpl.h>
#include "ServerRpc.c.h"

static void SessionRpc_Client_Register();
static void ClusterRpc_Client_Register();
static void NodeRpc_Client_Register();
static void WorkerRpc_Client_Register();

Zion::RPC_RESULT SRPC_UserLoginDone(Zion::HSERVER hServer, _U64 sndx, _U64 cndx)
{
	SessionRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(sndx)+_aligned_sizeof(cndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	buf.SetID(0, 0);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT SRPC_KickUser(Zion::HSERVER hServer, _U64 sndx)
{
	SessionRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(sndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	buf.SetID(0, 1);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT SRPC_ForwardUserData(Zion::HSERVER hServer, _U64 sndx, _U16 code, _U32 len, const _U8* data)
{
	SessionRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(sndx)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(0, 2);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT SRPC_SetNode(Zion::HSERVER hServer, _U64 sndx, _U32 nodeid, _U64 nndx, _U32 ip, _U16 port)
{
	SessionRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(sndx)+_aligned_sizeof(nodeid)+_aligned_sizeof(nndx)+_aligned_sizeof(ip)+_aligned_sizeof(port));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(ip)) return(RPC_RES_TMP);
	if(!buf.Serialize(port)) return(RPC_RES_TMP);
	buf.SetID(0, 3);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_UserLogin(Zion::HSERVER hServer, _U32 uid, const char* token, _U64 sndx)
{
	ClusterRpc_Client_Register();
	_U32 token__length = (_U32)(strlen(token)+1);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(uid)+_aligned_sizeof(token__length)+_buffer_alignof(sizeof(token[0])*token__length)+_aligned_sizeof(sndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(uid)) return(RPC_RES_TMP);
	if(!buf.Serialize(token__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(token__length, token)) return(RPC_RES_TMP);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	buf.SetID(1, 0);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_UserLogout(Zion::HSERVER hServer, _U32 uid, _U64 sndx)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(uid)+_aligned_sizeof(sndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(uid)) return(RPC_RES_TMP);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	buf.SetID(1, 1);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_KickUser(Zion::HSERVER hServer, _U32 uid)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(uid));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(uid)) return(RPC_RES_TMP);
	buf.SetID(1, 2);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_OnUserData(Zion::HSERVER hServer, _U64 cndx, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 3);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardUserDataByCNDX(Zion::HSERVER hServer, _U64 cndx, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 4);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardUserDataByUID(Zion::HSERVER hServer, _U32 uid, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(uid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(uid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 5);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardUserDataByAID(Zion::HSERVER hServer, _U32 aid, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(aid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(aid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 6);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardEventByCNDX(Zion::HSERVER hServer, _U64 cndx, _U32 nodeid, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(nodeid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 7);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardEventByUID(Zion::HSERVER hServer, _U32 uid, _U32 nodeid, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(uid)+_aligned_sizeof(nodeid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(uid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 8);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_ForwardEventByAID(Zion::HSERVER hServer, _U32 aid, _U32 nodeid, _U16 code, _U32 len, const _U8* data)
{
	ClusterRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(aid)+_aligned_sizeof(nodeid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(aid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(1, 9);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_NodeConnect(Zion::HSERVER hServer, _U64 cndx, _U32 nodeid, _U32 nodeseq, _U64 nndx)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(nodeid)+_aligned_sizeof(nodeseq)+_aligned_sizeof(nndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeseq)) return(RPC_RES_TMP);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	buf.SetID(1, 10);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_NodeDisconnect(Zion::HSERVER hServer, _U64 cndx, _U32 nodeid, _U32 nodeseq)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(nodeid)+_aligned_sizeof(nodeseq));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeseq)) return(RPC_RES_TMP);
	buf.SetID(1, 11);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_SetSessionWorkload(Zion::HSERVER hServer, const WORKLOAD_INFO& info)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(info));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(info)) return(RPC_RES_TMP);
	buf.SetID(1, 12);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_GetSessionWorkload(Zion::HSERVER hServer)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD);
	if(!buf) return(RPC_RES_OOM);
	buf.SetID(1, 13);
	return(buf.SendTo(hServer));
}

static bool CRPC_SessionWorkLoadResult_stub_0(Zion::HSERVER hServer, Zion::RPC_INPUT_BUF& buf)
{
	WORKLOAD_INFO* info;
	unsigned int* info__length;
	_U32* count;
	if(!buf.Serialize(info__length)) return false;
	if(!buf.Serialize(*info__length, info)) return false;
	if(!buf.Serialize(count)) return false;
	CRPC_SessionWorkLoadResult(hServer, info, *count);
	return true;
}

Zion::RPC_RESULT CRPC_SetNodeWorkload(Zion::HSERVER hServer, const WORKLOAD_INFO& info, _U32 type)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(info)+_aligned_sizeof(type));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(info)) return(RPC_RES_TMP);
	if(!buf.Serialize(type)) return(RPC_RES_TMP);
	buf.SetID(1, 14);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT CRPC_GetNodeWorkload(Zion::HSERVER hServer, _U32 type)
{
	ClusterRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(type));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(type)) return(RPC_RES_TMP);
	buf.SetID(1, 15);
	return(buf.SendTo(hServer));
}

static bool CRPC_NodeWorkLoadResult_stub_1(Zion::HSERVER hServer, Zion::RPC_INPUT_BUF& buf)
{
	_U32* type;
	WORKLOAD_INFO* info;
	unsigned int* info__length;
	_U32* count;
	if(!buf.Serialize(type)) return false;
	if(!buf.Serialize(info__length)) return false;
	if(!buf.Serialize(*info__length, info)) return false;
	if(!buf.Serialize(count)) return false;
	CRPC_NodeWorkLoadResult(hServer, *type, info, *count);
	return true;
}

Zion::RPC_RESULT NRPC_Connect(Zion::HSERVER hServer, _U64 cndx, _U32 nodeid, _U32 nodeseq, _U32 len, const _U8* data)
{
	NodeRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(cndx)+_aligned_sizeof(nodeid)+_aligned_sizeof(nodeseq)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(cndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeid)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeseq)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(2, 0);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT NRPC_SessionAck(Zion::HSERVER hServer, _U64 nndx, _U64 sndx)
{
	NodeRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(nndx)+_aligned_sizeof(sndx));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(sndx)) return(RPC_RES_TMP);
	buf.SetID(2, 1);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT NRPC_Disconnect(Zion::HSERVER hServer, _U64 nndx, _U32 nodeseq)
{
	NodeRpc_Client_Register();
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(nndx)+_aligned_sizeof(nodeseq));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(nodeseq)) return(RPC_RES_TMP);
	buf.SetID(2, 2);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT NRPC_OnUserData(Zion::HSERVER hServer, _U64 nndx, _U16 code, _U32 len, const _U8* data)
{
	NodeRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(nndx)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(2, 3);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT NRPC_OnForwardEvent(Zion::HSERVER hServer, _U64 nndx, _U16 code, _U32 len, const _U8* data)
{
	NodeRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(nndx)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(nndx)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(2, 4);
	return(buf.SendTo(hServer));
}

Zion::RPC_RESULT WRPC_DoRequest(Zion::HSERVER hServer, _U64 tid, _U16 code, _U32 len, const _U8* data)
{
	WorkerRpc_Client_Register();
	_U32 data__length = (_U32)(len);
	Zion::RPC_OUTPUT_BUF buf(RPC_PACKET_OVERHEAD+_aligned_sizeof(tid)+_aligned_sizeof(code)+_aligned_sizeof(len)+_aligned_sizeof(data__length)+_buffer_alignof(sizeof(data[0])*data__length));
	if(!buf) return(RPC_RES_OOM);
	if(!buf.Serialize(tid)) return(RPC_RES_TMP);
	if(!buf.Serialize(code)) return(RPC_RES_TMP);
	if(!buf.Serialize(len)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length)) return(RPC_RES_TMP);
	if(!buf.Serialize(data__length, data)) return(RPC_RES_TMP);
	buf.SetID(3, 0);
	return(buf.SendTo(hServer));
}

	static Zion::RPC_CBFUNC_STUB SessionRpc_callback_table[] = {
	NULL};
void SessionRpc_Client_Register() {
	Zion::lwrpc_cbinterface_table[0].cbfcount = sizeof(SessionRpc_callback_table)/sizeof(SessionRpc_callback_table[0]) - 1;
	Zion::lwrpc_cbinterface_table[0].cbfunc_tbl = SessionRpc_callback_table;
}
	static Zion::RPC_CBFUNC_STUB ClusterRpc_callback_table[] = {
	CRPC_SessionWorkLoadResult_stub_0,
	CRPC_NodeWorkLoadResult_stub_1,
	NULL};
void ClusterRpc_Client_Register() {
	Zion::lwrpc_cbinterface_table[1].cbfcount = sizeof(ClusterRpc_callback_table)/sizeof(ClusterRpc_callback_table[0]) - 1;
	Zion::lwrpc_cbinterface_table[1].cbfunc_tbl = ClusterRpc_callback_table;
}
	static Zion::RPC_CBFUNC_STUB NodeRpc_callback_table[] = {
	NULL};
void NodeRpc_Client_Register() {
	Zion::lwrpc_cbinterface_table[2].cbfcount = sizeof(NodeRpc_callback_table)/sizeof(NodeRpc_callback_table[0]) - 1;
	Zion::lwrpc_cbinterface_table[2].cbfunc_tbl = NodeRpc_callback_table;
}
	static Zion::RPC_CBFUNC_STUB WorkerRpc_callback_table[] = {
	NULL};
void WorkerRpc_Client_Register() {
	Zion::lwrpc_cbinterface_table[3].cbfcount = sizeof(WorkerRpc_callback_table)/sizeof(WorkerRpc_callback_table[0]) - 1;
	Zion::lwrpc_cbinterface_table[3].cbfunc_tbl = WorkerRpc_callback_table;
}
