////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#ifndef __ServerRpc__SERVER_STUB___
#define __ServerRpc__SERVER_STUB___

#include "ServerInc.h"

void SRPC_UserLoginDone(Zion::HCLIENT hClient, _U64 sndx, _U64 cndx);
void SRPC_KickUser(Zion::HCLIENT hClient, _U64 sndx);
void SRPC_ForwardUserData(Zion::HCLIENT hClient, _U64 sndx, _U16 code, _U32 len, const _U8* data);
void SRPC_SetNode(Zion::HCLIENT hClient, _U64 sndx, _U32 nodeid, _U64 nndx, _U32 ip, _U16 port);
void CRPC_UserLogin(Zion::HCLIENT hClient, _U32 uid, const char* token, _U64 sndx);
void CRPC_UserLogout(Zion::HCLIENT hClient, _U32 uid, _U64 sndx);
void CRPC_KickUser(Zion::HCLIENT hClient, _U32 uid);
void CRPC_OnUserData(Zion::HCLIENT hClient, _U64 cndx, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardUserDataByCNDX(Zion::HCLIENT hClient, _U64 cndx, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardUserDataByUID(Zion::HCLIENT hClient, _U32 uid, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardUserDataByAID(Zion::HCLIENT hClient, _U32 aid, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardEventByCNDX(Zion::HCLIENT hClient, _U64 cndx, _U32 nodeid, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardEventByUID(Zion::HCLIENT hClient, _U32 uid, _U32 nodeid, _U16 code, _U32 len, const _U8* data);
void CRPC_ForwardEventByAID(Zion::HCLIENT hClient, _U32 aid, _U32 nodeid, _U16 code, _U32 len, const _U8* data);
void CRPC_NodeConnect(Zion::HCLIENT hClient, _U64 cndx, _U32 nodeid, _U32 nodeseq, _U64 nndx);
void CRPC_NodeDisconnect(Zion::HCLIENT hClient, _U64 cndx, _U32 nodeid, _U32 nodeseq);
void CRPC_SetSessionWorkload(Zion::HCLIENT hClient, const WORKLOAD_INFO& info);
void CRPC_GetSessionWorkload(Zion::HCLIENT hClient);
Zion::RPC_RESULT CRPC_SessionWorkLoadResult(Zion::HCLIENT hClient, const WORKLOAD_INFO* info, _U32 count);
void CRPC_SetNodeWorkload(Zion::HCLIENT hClient, const WORKLOAD_INFO& info, _U32 type);
void CRPC_GetNodeWorkload(Zion::HCLIENT hClient, _U32 type);
Zion::RPC_RESULT CRPC_NodeWorkLoadResult(Zion::HCLIENT hClient, _U32 type, const WORKLOAD_INFO* info, _U32 count);
void NRPC_Connect(Zion::HCLIENT hClient, _U64 cndx, _U32 nodeid, _U32 nodeseq, _U32 len, const _U8* data);
void NRPC_SessionAck(Zion::HCLIENT hClient, _U64 nndx, _U64 sndx);
void NRPC_Disconnect(Zion::HCLIENT hClient, _U64 nndx, _U32 nodeseq);
void NRPC_OnUserData(Zion::HCLIENT hClient, _U64 nndx, _U16 code, _U32 len, const _U8* data);
void NRPC_OnForwardEvent(Zion::HCLIENT hClient, _U64 nndx, _U16 code, _U32 len, const _U8* data);
void WRPC_DoRequest(Zion::HCLIENT hClient, _U64 tid, _U16 code, _U32 len, const _U8* data);

void SessionRpc_Server_Register();
void ClusterRpc_Server_Register();
void NodeRpc_Server_Register();
void WorkerRpc_Server_Register();

#endif
