////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#ifndef __STRESSCASECONFIG_DDL_CODEGEN__
#define __STRESSCASECONFIG_DDL_CODEGEN__

#include <ZionDefines.h>
#include <ZionSTL.h>
#include <ZionUUID.h>
#include <DDL.h>
#include <DDLProxy.h>
#include <DDLStub.h>
#include <DDLReflect.h>

#pragma pack(push)
#pragma pack(4)

struct STRESSCASE_LOGIN_CONFIG
{
	_U32 reset_time;
	_U32 retry_time;
	_U32 disconnect_time;
};

namespace DDLReflect
{
	template<>
	const STRUCT_INFO* GetStruct<STRESSCASE_LOGIN_CONFIG>();
	extern STRUCT_INFO _rfl_struct_STRESSCASE_LOGIN_CONFIG_info;
}

struct STRESSCASE_LOGIN_STATUS
{
	_U32 failed_times;
	_U32 sucess_times;
};

namespace DDLReflect
{
	template<>
	const STRUCT_INFO* GetStruct<STRESSCASE_LOGIN_STATUS>();
	extern STRUCT_INFO _rfl_struct_STRESSCASE_LOGIN_STATUS_info;
}


#pragma pack(pop)

#endif
