////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#ifndef __COMMONDDL_DDL_CODEGEN__
#define __COMMONDDL_DDL_CODEGEN__

#pragma pack(push)
#pragma pack(4)

struct A_CONTENT_OBJECT
{
	A_UUID _uuid;
	DDL::String<100> _name;
};

namespace DDL
{
	template<>
	bool BufferReader::Read<A_CONTENT_OBJECT>(A_CONTENT_OBJECT& Value);
	template<>
	bool BufferWriter::Write<A_CONTENT_OBJECT>(const A_CONTENT_OBJECT& Value);
}

namespace DDLReflect
{
	template<>
	const STRUCT_INFO* GetStruct<A_CONTENT_OBJECT>();
	extern STRUCT_INFO _rfl_struct_A_CONTENT_OBJECT_info;
}

struct A_LIVE_OBJECT
{
	A_UUID _uuid;
};

namespace DDL
{
	template<>
	bool BufferReader::Read<A_LIVE_OBJECT>(A_LIVE_OBJECT& Value);
	template<>
	bool BufferWriter::Write<A_LIVE_OBJECT>(const A_LIVE_OBJECT& Value);
}

namespace DDLReflect
{
	template<>
	const STRUCT_INFO* GetStruct<A_LIVE_OBJECT>();
	extern STRUCT_INFO _rfl_struct_A_LIVE_OBJECT_info;
}


#pragma pack(pop)

#endif
