////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#ifndef __GAMEDDL_DDL_CODEGEN__
#define __GAMEDDL_DDL_CODEGEN__

#pragma pack(push)
#pragma pack(4)

#include "../LibCommon/CommonDDL.h"

struct A_GAME_OBJECT : A_LIVE_OBJECT
{
	A_UUID content_uuid;
};

namespace DDL
{
	template<>
	bool BufferReader::Read<A_GAME_OBJECT>(A_GAME_OBJECT& Value);
	template<>
	bool BufferWriter::Write<A_GAME_OBJECT>(const A_GAME_OBJECT& Value);
}

namespace DDLReflect
{
	template<>
	const STRUCT_INFO* GetStruct<A_GAME_OBJECT>();
	extern STRUCT_INFO _rfl_struct_A_GAME_OBJECT_info;
}


#pragma pack(pop)

#endif
