////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED. DO NOT MODIFY! //
////////////////////////////////////////////////

#include "CardGameDDL.h"

namespace DDL
{
	template<>
	bool BufferReader::Read<CARD_INVITATION>(CARD_INVITATION& Value)
	{
		if(!BufferReader::Read<A_CONTENT_OBJECT>(Value)) return false;
		if(!Read<_U32>(Value.iii)) return false;
		return true;
	}
	template<>
	bool BufferWriter::Write<CARD_INVITATION>(const CARD_INVITATION& Value)
	{
		if(!BufferWriter::Write<A_CONTENT_OBJECT>(Value)) return false;
		if(!Write<_U32>(Value.iii)) return false;
		return true;
	}
}

namespace DDLReflect
{

	static bool _struct_CARD_INVITATION_readproc(DDL::BufferReader& buf, void* data)
	{
		return buf.Read<CARD_INVITATION>(*((CARD_INVITATION*)data));
	}

	static bool _struct_CARD_INVITATION_writeproc(DDL::BufferWriter& buf, const void* data)
	{
		return buf.Write<CARD_INVITATION>(*((const CARD_INVITATION*)data));
	}

	static FIELD_INFO _struct_CARD_INVITATION_fieldinfo[] =
	{
		{TYPE_U32, "iii", 0, (_U16)ZION_OFFSETOF(CARD_INVITATION, iii), NULL, (_U16)-1, (_U16)-1, (_U16)0, (_U16)sizeof(_U32), NULL},
	};
	STRUCT_INFO _rfl_struct_CARD_INVITATION_info = { &_rfl_struct_A_CONTENT_OBJECT_info, "CARD_INVITATION", sizeof(CARD_INVITATION), 1, _struct_CARD_INVITATION_fieldinfo, _struct_CARD_INVITATION_readproc, _struct_CARD_INVITATION_writeproc };
	template<>
	const STRUCT_INFO* GetStruct<CARD_INVITATION>()
	{
		return &_rfl_struct_CARD_INVITATION_info;
	}
}

namespace DDLReflect
{
	static FIELD_INFO _class_CARDGAME_C2S_fieldinfos[] = 
	{
		// 0 Ping
		{0, NULL, 0, NULL, 0, 0, 0, 0},
	};
	static FUNCTION_INFO _class_CARDGAME_C2S_funcinfos[] = 
	{
		{"Ping", 0, _class_CARDGAME_C2S_fieldinfos+0},
	};
	static CLASS_INFO _class_CARDGAME_C2S_info = { 0, "CARDGAME_C2S", 1, _class_CARDGAME_C2S_funcinfos };
	template<>
	const CLASS_INFO* GetClass<CARDGAME_C2S>()
	{
		return &_class_CARDGAME_C2S_info;
	}
}

namespace DDLReflect
{
	static FIELD_INFO _class_CARDGAME_S2C_fieldinfos[] = 
	{
		// 0 Pong
		{0, NULL, 0, NULL, 0, 0, 0, 0},
	};
	static FUNCTION_INFO _class_CARDGAME_S2C_funcinfos[] = 
	{
		{"Pong", 0, _class_CARDGAME_S2C_fieldinfos+0},
	};
	static CLASS_INFO _class_CARDGAME_S2C_info = { 0, "CARDGAME_S2C", 1, _class_CARDGAME_S2C_funcinfos };
	template<>
	const CLASS_INFO* GetClass<CARDGAME_S2C>()
	{
		return &_class_CARDGAME_S2C_info;
	}
}

